# Generated by Django 3.2.3 on 2021-08-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=300)),
                ('detalhamento', models.CharField(max_length=300)),
                ('fabricanteVeiculo', models.CharField(max_length=100)),
                ('anoVeiculo', models.CharField(max_length=4)),
            ],
        ),
    ]
