# Generated by Django 3.2.3 on 2021-08-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliauto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultoria',
            name='data',
            field=models.DateTimeField(verbose_name='data'),
        ),
    ]
