# Generated by Django 3.2.3 on 2021-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliauto', '0002_alter_consultoria_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoria',
            name='modeloVeiculo',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
