# Generated by Django 3.2.3 on 2021-09-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliauto', '0004_consultoria_temconsultor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoria',
            name='plano',
            field=models.CharField(default='Completa', max_length=20),
            preserve_default=False,
        ),
    ]
