# Generated by Django 3.2.3 on 2021-09-26 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliauto', '0005_consultoria_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.CharField(max_length=300)),
                ('fabricanteVeiculo', models.CharField(max_length=100)),
                ('modeloVeiculo', models.CharField(max_length=100)),
                ('anoVeiculo', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='anoVeiculo',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='detalhamento',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='fabricanteVeiculo',
        ),
        migrations.RemoveField(
            model_name='consultoria',
            name='modeloVeiculo',
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliauto.consultoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliauto.consultoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultoria',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliauto.veiculo'),
        ),
    ]
