# Generated by Django 3.2.3 on 2021-09-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliauto', '0006_auto_20210926_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='consultoria',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='consultoria',
        ),
        migrations.AddField(
            model_name='consultoria',
            name='cliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliauto.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultoria',
            name='mecanico',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliauto.mecanico'),
            preserve_default=False,
        ),
    ]
