# Generated by Django 3.2.3 on 2021-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliauto', '0007_auto_20210930_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultoria',
            name='mecanico',
            field=models.IntegerField(),
        ),
    ]
