# Generated by Django 3.2.3 on 2021-09-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliauto', '0008_alter_consultoria_mecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultoria',
            name='cliente',
            field=models.IntegerField(),
        ),
    ]
